languageCode = 'pt-br'
title = 'Arthur Correa'
theme = 'hello-friend'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1
enableRobotsTXT = true
[[params.social]]
  name = "github"
  url = "https://github.com/seuusuario"

