baseURL = 'https://arthuralcorrea.github.io/'
languageCode = 'pt-br'
title = 'Arthur Correa'
theme = 'blog-awesome'
[[params.socialIcons]]
name = "github"
url = "https://github.com/arthuralcorrea"
[[params.socialIcons]]
name = "twitter"
url = "https://x.com/arthurac1337"
[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@arthurac1337"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
