languageCode = 'pt-br'
title = 'Arthur Correa'
theme = 'hello-friend'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1
